name: Input Values
on:
  workflow_call:
    outputs:
      reversedString: 
        description: "The Reversed string"
        value: ${{ jobs.reverse-string.outputs.randomString }}
  workflow_dispatch:
    inputs:
      message:
        description: Any Message you want to send
        required: false
        default: hello world

jobs:
  reverse-string:
    runs-on: ubuntu-latest
    outputs:
      reversedString: ${{ steps.reverse.outputs.randomString }}
    steps:
    - run: |
        echo "reversedString=$(echo '${{ github.event.inputs.message }}' | rev)" >> $GITHUB_OUTPUT
        echo '${{ github.event.inputs.message }}' | rev
      name: Reverse the String
      id: reverse