name: Output Values
on:
  workflow_call:
    outputs:
      randomString: 
        value: ${{ jobs.random-string.outputs.randomString }}

jobs:
  random-string:
    runs-on: ubuntu-latest
    outputs:
      randomString: ${{ steps.generate.outputs.randomString }}
    steps:
    - run: |
        echo "::set-output name=randomString::$(echo $RANDOM | md5sum | head -c 20)" 
        echo $RANDOM | md5sum | head -c 20
      name: Generate Random String
      id: generate