name: Read Outputs
on:
  workflow_call:
    inputs:
      randomString:
        type: string
        required: true
      reversedString:
        type: string
        required: true
jobs:
  print-outputs:
    runs-on: ubuntu-latest
    steps:
    - name: Print Output Values
      run: |
        echo '${{ github.event.inputs.randomString }}'
        echo '${{ github.event.inputs.reversedString }}'