name: Reusable Workflow
on:
  workflow_dispatch:
    inputs:
      message:
        description: Any Message you want to send
        required: false
        default: hello world

jobs:
  output-values:
    name: Get Output Values
    uses: ./.github/workflows/outputs.yml

  use-inputs:
    name: Use Caller inputs
    needs: output-values
    uses: ./.github/workflows/inputs.yml

  read-outputs:
    name: Read the outpus generated on the workflow
    needs: [output-values, use-inputs]
    uses: ./.github/workflows/read-outputs.yml
    with:
      randomString: ${{ needs.output-values.outputs.randomString }}
      reversedString: ${{ needs.use-inputs.outputs.reversedString }}
    secrets: inherit
  