name: Reusable Workflow
on:
  workflow_dispatch:
    inputs:
      message:
        description: Any Message you want to send
        required: false
        default: hello world

jobs:
  output-values:
    name: Get Output Values
    uses: ./.github/workflows/outputs.yml

  use-inputs:
    name: Use Caller inputs
    needs: output-values
    uses: ./.github/workflows/inputs.yml

  simple:
    runs-on: ubuntu-latest
    needs: use-inputs
    steps:
      - run: echo ${{ needs.output-values.outputs.randomString }} ${{ needs.use-inputs.outputs.reversedString }}

  read-outputs:
    name: Read the outpus generated on the workflow
    needs: use-inputs
    uses: ./.github/workflows/read-outputs.yml
    with:
      randomString: ${{ needs.output-values.outputs.randomString }}
      reversedString: ${{ needs.use-inputs.outputs.reversedString }}
  